"""A2A server for a Demiurge-minted Archon on the Claude Code CLI runtime.

Generated by Demiurge's claude-cli adapter (ADR 0006). The spec next to this
file (archon.agf.yaml) is the configuration; this server loads and serves it
and holds no per-Archon logic. Delegated tasks execute the spec's agf.react
policy by shelling out to the `claude` CLI (`claude -p`), which bills the
operator's Claude subscription — ANTHROPIC_API_KEY is deliberately scrubbed
from the child environment so a stray key can never switch the Archon to
metered API billing.
"""

import argparse
import asyncio
import json
import os
import shutil
from pathlib import Path
from typing import Any

import uvicorn
import yaml
from a2a.helpers import (
    get_message_text,
    new_task_from_user_message,
    new_text_message,
    new_text_part,
)
from a2a.server.agent_execution import AgentExecutor, RequestContext
from a2a.server.events import EventQueue
from a2a.server.request_handlers import DefaultRequestHandler
from a2a.server.routes import create_agent_card_routes, create_jsonrpc_routes
from a2a.server.tasks import InMemoryTaskStore, TaskUpdater
from a2a.types import AgentCapabilities, AgentCard, AgentInterface, AgentSkill
from a2a.types.a2a_pb2 import TaskState
from starlette.applications import Starlette

SPEC_PATH = Path(__file__).resolve().parent / "archon.agf.yaml"
MCP_CONFIG_PATH = Path(__file__).resolve().parent / "mcp-servers.json"
CLI_MCP_CONFIG_PATH = Path(__file__).resolve().parent / "cli-mcp-config.json"

# Overridable knobs (env), all optional:
CLI_BIN_ENV = "CLAUDE_CLI_BIN"  # path to the claude CLI (default: "claude" on PATH)
PERMISSION_MODE_ENV = "CLAUDE_CLI_PERMISSION_MODE"  # e.g. "default", "acceptEdits"
DEFAULT_TIMEOUT_SECONDS = 600.0  # used when the spec declares no duration budget


def mcp_options(
    spec: dict[str, Any], config_path: Path = MCP_CONFIG_PATH
) -> tuple[dict[str, Any], list[str]]:
    """Map the spec's mcp_servers grants onto real connections + allowed tools.

    The spec declares portable grants (alias, server_ref, allowed_tools); the
    Agent Format standard assigns mapping server_ref to real connection
    details to the runtime owner. That mapping lives in mcp-servers.json next
    to this file (see README) — the same operator contract as the claude-sdk
    scaffold. Returns (mcp_servers, allowed_tools); grants with no mapping
    entry are skipped — the Archon simply runs without them.
    """
    grants = (spec.get("action_space") or {}).get("mcp_servers") or []
    if not grants or not config_path.is_file():
        return {}, []
    mapping = json.loads(config_path.read_text(encoding="utf-8"))
    servers: dict[str, Any] = {}
    allowed_tools: list[str] = []
    for grant in grants:
        alias = grant["alias"]
        connection = mapping.get(alias)
        if connection is None:
            continue
        connection = {k: v for k, v in connection.items() if k != "server_ref"}
        servers[alias] = connection
        tools = grant.get("allowed_tools") or []
        if tools:
            allowed_tools.extend(
                f"mcp__{alias}__{tool if isinstance(tool, str) else tool['name']}" for tool in tools
            )
        else:
            allowed_tools.append(f"mcp__{alias}")  # whole-server grant
    return servers, allowed_tools


def builtin_tools(spec: dict[str, Any]) -> list[str]:
    """Runtime-builtin tool grants from the spec's action_space.local_tools.

    On this runtime a local tool's ``name`` is a Claude Code tool name or
    specifier (e.g. ``Bash``, ``WebSearch``, ``Bash(python *)``); it defaults
    to the alias. These become `--allowedTools` entries, i.e. pre-approved.
    """
    grants = (spec.get("action_space") or {}).get("local_tools") or []
    return [grant.get("name") or grant["alias"] for grant in grants]


def write_cli_mcp_config(servers: dict[str, Any], path: Path = CLI_MCP_CONFIG_PATH) -> Path | None:
    """Render the mapped servers in the CLI's `--mcp-config` shape."""
    if not servers:
        return None
    path.write_text(json.dumps({"mcpServers": servers}, indent=2) + "\n", encoding="utf-8")
    return path


def scrubbed_env() -> dict[str, str]:
    """Child env for the CLI: never let a stray API key force metered billing."""
    env = os.environ.copy()
    env.pop("ANTHROPIC_API_KEY", None)
    return env


def build_cli_command(
    *,
    cli_bin: str,
    user_request: str,
    instructions: str,
    model: str | None,
    allowed_tools: list[str],
    mcp_config_file: Path | None,
    permission_mode: str | None,
) -> list[str]:
    """Compose the one-shot `claude -p` invocation for a delegated task (pure)."""
    command = [
        cli_bin,
        "-p",
        user_request,
        "--output-format",
        "text",
        "--append-system-prompt",
        instructions,
    ]
    if model:
        command += ["--model", model]
    if allowed_tools:
        command += ["--allowedTools", ",".join(allowed_tools)]
    if mcp_config_file is not None:
        # --strict-mcp-config keeps the Archon to exactly its granted servers,
        # ignoring whatever else the operator's machine has configured.
        command += ["--mcp-config", str(mcp_config_file), "--strict-mcp-config"]
    if permission_mode:
        command += ["--permission-mode", permission_mode]
    return command


class ArchonExecutor(AgentExecutor):
    """Runs the spec's agf.react policy on the Claude Code CLI."""

    def __init__(self, spec: dict[str, Any]) -> None:
        config = spec["execution_policy"]["config"]
        self._model: str | None = config.get("model")
        self._max_steps: int = int(config.get("max_steps", 10))
        # The CLI has no --max-turns; the step budget rides the system prompt
        # (advisory) and the duration budget is the hard rail (timeout below).
        self._instructions: str = (
            config["instructions"]
            + f"\n\nBudget: aim to finish within about {self._max_steps} tool-use steps."
        )
        budget = (spec.get("constraints") or {}).get("budget") or {}
        self._timeout: float = float(budget.get("max_duration_seconds") or DEFAULT_TIMEOUT_SECONDS)
        servers, mcp_tools = mcp_options(spec)
        self._allowed_tools = builtin_tools(spec) + mcp_tools
        self._mcp_config_file = write_cli_mcp_config(servers)

    async def _invoke(self, user_request: str) -> str:
        # Resolved lazily so the server can boot and serve its agent card
        # (health checks, admission plumbing) even when the CLI is missing.
        cli_bin = os.environ.get(CLI_BIN_ENV, "claude")
        cli_bin = shutil.which(cli_bin) or cli_bin
        command = build_cli_command(
            cli_bin=cli_bin,
            user_request=user_request,
            instructions=self._instructions,
            model=self._model,
            allowed_tools=self._allowed_tools,
            mcp_config_file=self._mcp_config_file,
            permission_mode=os.environ.get(PERMISSION_MODE_ENV),
        )
        process = await asyncio.create_subprocess_exec(
            *command,
            cwd=Path(__file__).resolve().parent,
            env=scrubbed_env(),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        try:
            stdout, stderr = await asyncio.wait_for(process.communicate(), timeout=self._timeout)
        except TimeoutError:
            process.kill()
            await process.wait()
            raise RuntimeError(
                f"claude CLI exceeded the {self._timeout:.0f}s duration budget"
            ) from None
        if process.returncode != 0:
            detail = (stderr or stdout or b"").decode("utf-8", errors="replace").strip()
            raise RuntimeError(f"claude CLI exited with code {process.returncode}: {detail[:2000]}")
        text = (stdout or b"").decode("utf-8", errors="replace").strip()
        return text or "(the Archon produced no text output)"

    async def execute(self, context: RequestContext, event_queue: EventQueue) -> None:
        task = context.current_task
        if not task:
            task = new_task_from_user_message(context.message)
            await event_queue.enqueue_event(task)
        updater = TaskUpdater(event_queue=event_queue, task_id=task.id, context_id=task.context_id)
        await updater.update_status(
            state=TaskState.TASK_STATE_WORKING,
            message=new_text_message("Working..."),
        )
        user_request = get_message_text(context.message)
        if user_request:
            try:
                result = await self._invoke(user_request)
            except Exception as error:  # surface runtime failures to the caller, don't crash
                result = f"Archon runtime error: {error}"
        else:
            result = "No text input was provided."
        await updater.add_artifact(parts=[new_text_part(text=result, media_type="text/plain")])
        await updater.update_status(
            state=TaskState.TASK_STATE_COMPLETED,
            message=new_text_message("Done."),
        )

    async def cancel(self, context: RequestContext, event_queue: EventQueue) -> None:
        raise NotImplementedError("cancel is not supported")


def build_app(spec: dict[str, Any], port: int) -> Starlette:
    metadata = spec["metadata"]
    endpoint = f"http://127.0.0.1:{port}"
    skill = AgentSkill(
        id=metadata["id"],
        name=metadata["name"],
        description=metadata["description"],
        tags=["demiurge", "archon"],
        input_modes=["text/plain"],
        output_modes=["text/plain"],
    )
    card = AgentCard(
        name=metadata["name"],
        description=metadata["description"],
        version=metadata["version"],
        default_input_modes=["text/plain"],
        default_output_modes=["text/plain"],
        capabilities=AgentCapabilities(streaming=True),
        supported_interfaces=[
            AgentInterface(protocol_binding="JSONRPC", url=endpoint, protocol_version="1.0")
        ],
        skills=[skill],
    )
    handler = DefaultRequestHandler(
        agent_executor=ArchonExecutor(spec),
        task_store=InMemoryTaskStore(),
        agent_card=card,
    )
    routes = [*create_agent_card_routes(card), *create_jsonrpc_routes(handler, "/")]
    return Starlette(routes=routes)


def main() -> None:
    parser = argparse.ArgumentParser(description="Serve a Demiurge Archon over A2A.")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=9999)
    args = parser.parse_args()
    spec = yaml.safe_load(SPEC_PATH.read_text(encoding="utf-8"))
    uvicorn.run(build_app(spec, args.port), host=args.host, port=args.port)


if __name__ == "__main__":
    main()
