"""A2A server for a Demiurge-minted Archon on the Claude Agent SDK runtime.

Generated by Demiurge's claude-sdk adapter (ADR 0005). The spec next to this
file (archon.agf.yaml) is the configuration; this server loads and serves it
and holds no per-Archon logic.
"""

import argparse
import json
from pathlib import Path
from typing import Any

import uvicorn
import yaml
from a2a.helpers import (
    get_message_text,
    new_task_from_user_message,
    new_text_message,
    new_text_part,
)
from a2a.server.agent_execution import AgentExecutor, RequestContext
from a2a.server.events import EventQueue
from a2a.server.request_handlers import DefaultRequestHandler
from a2a.server.routes import create_agent_card_routes, create_jsonrpc_routes
from a2a.server.tasks import InMemoryTaskStore, TaskUpdater
from a2a.types import AgentCapabilities, AgentCard, AgentInterface, AgentSkill
from a2a.types.a2a_pb2 import TaskState
from starlette.applications import Starlette

SPEC_PATH = Path(__file__).resolve().parent / "archon.agf.yaml"
MCP_CONFIG_PATH = Path(__file__).resolve().parent / "mcp-servers.json"


def mcp_options(
    spec: dict[str, Any], config_path: Path = MCP_CONFIG_PATH
) -> tuple[dict[str, Any], list[str]]:
    """Map the spec's mcp_servers grants onto Claude Agent SDK options.

    The spec declares portable grants (alias, server_ref, allowed_tools); the
    Agent Format standard assigns mapping server_ref to real connection
    details to the runtime owner. That mapping lives in mcp-servers.json next
    to this file (see README). Returns (mcp_servers, allowed_tools); grants
    with no mapping entry are skipped — the Archon simply runs without them.
    """
    grants = (spec.get("action_space") or {}).get("mcp_servers") or []
    if not grants or not config_path.is_file():
        return {}, []
    mapping = json.loads(config_path.read_text(encoding="utf-8"))
    servers: dict[str, Any] = {}
    allowed_tools: list[str] = []
    for grant in grants:
        alias = grant["alias"]
        connection = mapping.get(alias)
        if connection is None:
            continue
        servers[alias] = connection
        tools = grant.get("allowed_tools") or []
        if tools:
            allowed_tools.extend(
                f"mcp__{alias}__{tool if isinstance(tool, str) else tool['name']}" for tool in tools
            )
        else:
            allowed_tools.append(f"mcp__{alias}")  # whole-server grant
    return servers, allowed_tools


class ArchonExecutor(AgentExecutor):
    """Runs the spec's agf.react policy on the Claude Agent SDK."""

    def __init__(self, spec: dict[str, Any]) -> None:
        config = spec["execution_policy"]["config"]
        self._instructions: str = config["instructions"]
        self._model: str | None = config.get("model")
        self._max_steps: int = int(config.get("max_steps", 10))
        self._mcp_servers, self._allowed_tools = mcp_options(spec)

    async def _invoke(self, user_request: str) -> str:
        # Imported lazily so the server can boot and serve its agent card
        # even when the runtime SDK is missing or unauthenticated.
        from claude_agent_sdk import AssistantMessage, ClaudeAgentOptions, TextBlock, query

        options = ClaudeAgentOptions(
            system_prompt=self._instructions,
            model=self._model,
            max_turns=self._max_steps,
            mcp_servers=self._mcp_servers,
            allowed_tools=self._allowed_tools,
        )
        chunks: list[str] = []
        async for message in query(prompt=user_request, options=options):
            if isinstance(message, AssistantMessage):
                chunks.extend(
                    block.text for block in message.content if isinstance(block, TextBlock)
                )
        return "\n\n".join(chunks) or "(the Archon produced no text output)"

    async def execute(self, context: RequestContext, event_queue: EventQueue) -> None:
        task = context.current_task
        if not task:
            task = new_task_from_user_message(context.message)
            await event_queue.enqueue_event(task)
        updater = TaskUpdater(event_queue=event_queue, task_id=task.id, context_id=task.context_id)
        await updater.update_status(
            state=TaskState.TASK_STATE_WORKING,
            message=new_text_message("Working..."),
        )
        user_request = get_message_text(context.message)
        if user_request:
            try:
                result = await self._invoke(user_request)
            except Exception as error:  # surface runtime failures to the caller, don't crash
                result = f"Archon runtime error: {error}"
        else:
            result = "No text input was provided."
        await updater.add_artifact(parts=[new_text_part(text=result, media_type="text/plain")])
        await updater.update_status(
            state=TaskState.TASK_STATE_COMPLETED,
            message=new_text_message("Done."),
        )

    async def cancel(self, context: RequestContext, event_queue: EventQueue) -> None:
        raise NotImplementedError("cancel is not supported")


def build_app(spec: dict[str, Any], port: int) -> Starlette:
    metadata = spec["metadata"]
    endpoint = f"http://127.0.0.1:{port}"
    skill = AgentSkill(
        id=metadata["id"],
        name=metadata["name"],
        description=metadata["description"],
        tags=["demiurge", "archon"],
        input_modes=["text/plain"],
        output_modes=["text/plain"],
    )
    card = AgentCard(
        name=metadata["name"],
        description=metadata["description"],
        version=metadata["version"],
        default_input_modes=["text/plain"],
        default_output_modes=["text/plain"],
        capabilities=AgentCapabilities(streaming=True),
        supported_interfaces=[
            AgentInterface(protocol_binding="JSONRPC", url=endpoint, protocol_version="1.0")
        ],
        skills=[skill],
    )
    handler = DefaultRequestHandler(
        agent_executor=ArchonExecutor(spec),
        task_store=InMemoryTaskStore(),
        agent_card=card,
    )
    routes = [*create_agent_card_routes(card), *create_jsonrpc_routes(handler, "/")]
    return Starlette(routes=routes)


def main() -> None:
    parser = argparse.ArgumentParser(description="Serve a Demiurge Archon over A2A.")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=9999)
    args = parser.parse_args()
    spec = yaml.safe_load(SPEC_PATH.read_text(encoding="utf-8"))
    uvicorn.run(build_app(spec, args.port), host=args.host, port=args.port)


if __name__ == "__main__":
    main()
